export const TASKS_FETCH_REQUEST = 'TASKS_FETCH_REQUEST';
export const TASKS_FETCH_SUCCESS = 'TASKS_FETCH_SUCCESS';
export const TASKS_FETCH_FAIL = 'TASKS_FETCH_FAIL';

export const CREATE_NEW_TASK_REQUEST = 'CREATE_NEW_TASK_REQUEST';
export const NEW_TASK_CREATED_SUCCESSFULLY = 'NEW_TASK_CREATED_SUCCESSFULLY';
export const NEW_TASK_CREATED_FAILED = 'NEW_TASK_CREATED_FAILED';

export const TASK_REMOVE_REQUEST = 'TASK_REMOVE_REQUEST';
export const TASK_REMOVED_SUCCESSFULLY = 'TASK_REMOVED_SUCCESSFULLY';
export const TASK_REMOVED_FAILED = 'TASK_REMOVED_FAILED';

export const UNDEFINED_ERROR_MESSAGE = 'Ooops, something went wrong';
